sudo: required

language: node_js
node_js:
  - "8.11.4"

services:
  - docker

before_install: 
  - docker build -t artyom366/docker-react -f Dockerfile.dev .

service: 
  - docker run artyom366/docker-react npm run test -- --coverage